name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [17]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ matrix.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ matrix.os }}-

      - name: Grant execute permission for Gradle wrapper (if on Unix)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: List Projects
        run: ./gradlew projects
        shell: bash

      - name: List Available Tasks
        run: ./gradlew tasks --all
        shell: bash

      - name: Build the headless module
        run: ./gradlew :headless:build
        shell: bash

      - name: Run tests in headless module (includes JaCoCo report generation)
        run: ./gradlew :headless:test
        shell: bash

      - name: Upload JaCoCo code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report-${{ matrix.os }}
          path: headless/build/reports/jacoco/test/html/**

      - name: Uplaod JAR
        uses: actions/upload-artifact@v4
        with:
          name: builds.jar
          path: headless/build/libs/builds.jar
 

